name: Build

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2.2.1
        with:
          tag_name: v0.2.0

      - name: Set up Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version: '1.22'
          check-latest: true

      - name: Install dependencies
        run: go mod download

      - name: Create dist directory
        run: mkdir -p dist

      - name: Build for Linux AMD64
        run: GOOS=linux GOARCH=amd64 go build -v -o dist/girus-linux-amd64 -ldflags="-X 'github.com/badtuxx/girus-cli/cmd.Version=${{ github.ref_name }}'" ./main.go

      - name: Build for Linux ARM64
        run: GOOS=linux GOARCH=arm64 go build -v -o dist/girus-linux-arm64 -ldflags="-X 'github.com/badtuxx/girus-cli/cmd.Version=${{ github.ref_name }}'" ./main.go

      - name: Build for macOS AMD64 (Intel)
        run: GOOS=darwin GOARCH=amd64 go build -v -o dist/girus-darwin-amd64 -ldflags="-X 'github.com/badtuxx/girus-cli/cmd.Version=${{ github.ref_name }}'" ./main.go

      - name: Build for macOS ARM64 (Apple Silicon)
        run: GOOS=darwin GOARCH=arm64 go build -v -o dist/girus-darwin-arm64 -ldflags="-X 'github.com/badtuxx/girus-cli/cmd.Version=${{ github.ref_name }}'" ./main.go

      - name: Build for Windows
        run: GOOS=windows GOARCH=amd64 go build -v -o dist/girus-windows-amd64.exe -ldflags="-X 'github.com/badtuxx/girus-cli/cmd.Version=${{ github.ref_name }}'" ./main.go

      - name: Create Release
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2.2.1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/girus-linux-amd64
            dist/girus-linux-arm64
            dist/girus-darwin-amd64
            dist/girus-darwin-arm64
            dist/girus-windows-amd64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
